### ISSUE TITLE
download info failed

### ISSUE THREAD

**Issue by 89z** [GoneToneStudio/node-google-play-api#18]
Using this program, everything works:

~~~js
const GooglePlayAPI = require('@gonetone/google-play-api');
var gpAPI = new GooglePlayAPI("srp...@gmail.com", "33783f43efa...");

gpAPI.getGoogleToken(
   'oauth2_4/0AX4XfWitLKPqHVx072mfsTFrsGTv6u1HMFIRxHBh4tpGftkbJXc3GHVI7zV_t...',
   'token.txt'
).then(async (token) => {
   await gpAPI.googleAuth(token);
   const downloadInfo = await gpAPI.downloadInfo('com.github.android');
   console.log(downloadInfo);
});
~~~

but if I change the app, it fails:

~~~
Error: Get "air.ITVMobilePlayer" download info failed, may be the device does not support.
    at GooglePlayAPI.downloadInfo (D:\Desktop\etc\node_modules\@gonetone\google-play-api\src\GooglePlayAPI.js:386:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\Desktop\etc\play.js:17:25
~~~

its a valid app:

https://play.google.com/store/apps/details?id=air.ITVMobilePlayer

**Comment by GoneTone** [comment]
Device does not support.
Please use a supported device to get a GSF ID and try again.
